
# This file should be copied as config.yml and edited.

# Marketing campaign:

mc:
  datadir: "/PATH/TO/DATA"
  datafile: "marketing_campaign.csv"
  metafile: "marketing-campaign-muuttujat.xlsx"
  varsfile: "mc-data-2023-XX-YY.csv"
  bgrvfile: "mc-bg-2023-XX-YY.csv"
  transpose: False
  index_col: 0
  n_clusters_kmeans: 6
  pointsize: 5
  outdir: "mc"